# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
    paths-ignore:
    - '.github/**'
  pull_request:
    branches: [ develop ]
    paths-ignore:
    - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: test-anl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@main
        with:
          repository: arjun-raj-kuppala/test-backend1
          path: ./test-backend1
          
      - uses: actions/checkout@main
        with:
          repository: arjun-raj-kuppala/test-backend2
          path: ./test-backend2
      
      - name: Check directory structure
        run: |
             cd $GITHUB_WORKSPACE
             ls -lart
      
      - name: Running test-common build
        run: |
            cd $GITHUB_WORKSPACE
            echo "starting the build"
            ./build.sh
            echo "build completed successfully"
      
      - name: Running tests on backend1
        run: |
             echo "starting test execution on backend1"
             cd $GITHUB_WORKSPACE
             ./test.sh
             echo "test execution completed"
             
      - name: Running tests on backend2
        run: |
             echo "starting test execution on backend2"
             cd $GITHUB_WORKSPACE
             ./test.sh
             echo "test execution completed on backend2"
             
      - name: Clean temp directory
        run: |
             cd $GITHUB_WORKSPACE
             rm -rf *
             echo "cleaned up the workspace"

